#!/bin/bash
python3 train.py --network-type GEO_GCN --dataset Decagon --use-features --MTL --epochs 1000 --score loss_sum --hidden-dim 36 --shuffle --disease_class "nervous system disease" --expt_name neuro_MT
